"""Fix prescription and relationship structure

Revision ID: 0601442ad45a
Revises: a0aea79621e5
Create Date: 2025-06-26 17:40:32.913569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0601442ad45a'
down_revision = 'a0aea79621e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('time')
        batch_op.drop_column('field')

    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['appointment_id'])

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.alter_column('medications',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint('prescription_health_record_id_fkey', type_='foreignkey')
        batch_op.drop_column('health_record_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_record_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('prescription_health_record_id_fkey', 'health_record', ['health_record_id'], ['id'])
        batch_op.alter_column('medications',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('condition',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
