"""Updated health record model with relationships

Revision ID: 5be5d7187c48
Revises: 1955de15bad3
Create Date: 2025-06-26 17:20:55.768749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be5d7187c48'
down_revision = '1955de15bad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.alter_column('lab_technician_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['appointment_id'])
        batch_op.drop_constraint('health_record_prescription_id_fkey', type_='foreignkey')
        batch_op.drop_column('prescription_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('health_record_prescription_id_fkey', 'prescription', ['prescription_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('lab_technician_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
