"""Increase password_hash length to 255

Revision ID: 62df3df2f242
Revises: 94d22cdedda5
Create Date: 2025-06-27 19:00:16.003361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62df3df2f242'
down_revision = '94d22cdedda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
