"""Fix health_record–prescription relationship

Revision ID: a0aea79621e5
Revises: 5be5d7187c48
Create Date: 2025-06-26 17:29:46.719088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0aea79621e5'
down_revision = '5be5d7187c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.alter_column('lab_technician_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('condition',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint('health_record_appointment_id_key', type_='unique')

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_record_id', sa.Integer(), nullable=True))
        batch_op.alter_column('medications',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'health_record', ['health_record_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('medications',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('health_record_id')

    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.create_unique_constraint('health_record_appointment_id_key', ['appointment_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('condition',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('lab_technician_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
